name: final_chit_chat
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/chat_app_logo.png
